# Generated by Django 4.2.11 on 2026-03-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("flagged_count", models.IntegerField()),
                ("score", models.FloatField()),
                ("user_email", models.EmailField(max_length=254)),
            ],
        ),
    ]
